### ISSUE TITLE
Fixing OELint findings in recipes doesn't necessarily invalidate previous runs of sca_oelint_core

### ISSUE THREAD

**Issue by pasweistorz** [priv-kweihmann/meta-sca#10927] opened 2023-02-03 14:36 UTC
**Describe the bug**
Hi, we're using the `oelint` module from your layer. It reported an issue in a `bbappend` file for `networkmanager-qt` from `yocto-meta-kf5` layer. The issue reported was to use `SRC_URI:append` instead of using `SRC_URI +=` (`oelint.oelint_vars_srcuriappend`). We fixed the issue but retriggering a build still reported the error until we enforced running the task `sca_oelint_core` via `bitbake -C`.

We think that modifying a recipe (fixing an issue) should automatically invalidate the previous run of the `sca_oelint_core` task. It shouldn't be needed to manually invalidate the previous run by enforcing the `sca_oelint_core` task.

**Used layer**
- hash of meta-sca layer: 07659809d
- poky hash: 868eb84303
- hashes of additional layer yocto-meta-kf5 9f7a077 meta-openembedded 0782ea454
- our own layer

**Used configuration**
```
INHERIT += "sca"
SCA_AVAILABLE_MODULES = "\
    oelint \
"
SCA_SPARE_LAYER = "\
    core \
    kf6 \
    meta-python \
    meta-sca \
    networking-layer \
    openembedded-layer \
"
SCA_VERBOSE_OUTPUT = "1"
SCA_WARNING_LEVEL = "info"
SCA_OELINT_CUSTOM_RULES = ""
```

**Comment by priv-kweihmann** [comment] 2023-02-03 15:46
I’m not sure if this is a bug - but it is definitely be a problem.
So all the sca-tasks are bound to do_compile/do_configure or similar tasks bitbake/oe-core provides.

What bitbake does is turn the recipes into shell scripts reflecting all the settings made from the bb/bbappends.

In your case I think changing `A += "1"` into `A:append = " 1"`  results in the same `A = "<preamble> 1"` in the shell script.
Thus for bitbake none of the important task hashes changes, therefore nothing will get reexecuted.
From my point of view this is intended behavior (by bitbake) and I’m not sure what to do about it, as this layer just hooks up on the tasking system.

What I normally do for recipes that just got these style kind of issues is to invalidate the cache using `bitbake networkmanager-qt -c cleansstate` which guarantees to have all the tasks running.
As I don’t know the setup on your end is working (if it’s CI with a shared sstate cache or just a local build), different workaround can be applied - and if nothing helps you can still use the inline suppression feature of oelint: in your case `' nooelint: oelint.oelint_vars_srcuriappend` right above the line that the tool is complaining about.

Another option is to active the `SCA_FORCE_RUN` feature to have all the tasks running everytime you do a build (see https://github.com/priv-kweihmann/meta-sca/blob/master/docs/conf/global.md) - for a small set of SCA_AVAILABLE_MODULES and a small software stack that might be a feasible option - for larger software builds that might end up being very costly.

And one more option that I see:
- you could write `SRC_URI:append = "  something"` so adding two spaces as this would result in a hash change and should trigger a new run (but this is only meant for testing purpose locally)

**Comment by pasweistorz** [comment] 2023-02-03 15:59
Thank you very much for the fast answer.

We're using a CI system with a shared sstate cache.

Using `SCA_FORCE_RUN` seems to be no option for us as it triggered a lot of rebuilds. As we like to fix the issues to improve the quality of our recipes we also don't want to disable the warnings.

Locally we can workaround this issue by cleaning the sstate as you suggested. The problematic thing is the shared sstate cache used in our CI. We had to clean the corresponding task in it to let our builds pass the CI.

Do you have some other ideas what we could do about this?

**Comment by priv-kweihmann** [comment] 2023-02-03 16:07
then I only see the options
- to manipulate the effective variable set to provoke a rebuild
- use of inline suppression after the fix was applied

**Comment by pasweistorz** [comment] 2023-02-03 17:04
I don't know if it's possible but wouldn't it be correct to make the `sca_oelint_core` task also dependent on the recipe hash instead of just only on the `do_compile` task?

**Comment by priv-kweihmann** [comment] 2023-02-04 09:29
It would, but I personally don’t know if there is such a hash for the plain content of all the files involved.
Btw do_compile depends on the task hashes of do_configure, do_fetch and do_unpack so any previous task being rerun automatically will invalidate the hash of do_compile.
Anyway I will have a look, but it doesn’t look good tbh

**Comment by priv-kweihmann** [comment] 2023-02-15 13:12
Just had an in-depth look if bitbake does provide anything like this, sadly it doesn’t - there are just "task" hashes, based on the parsed recipe info (incl. conf and bbappend files).
One could theoretically use a parser event hook and manually calculate the hash over everything in [BBINCLUDED](https://docs.yoctoproject.org/bitbake/2.0/bitbake-user-manual/bitbake-user-manual-ref-variables.html#term-BBINCLUDED), but that is super costly.
If you really require that and can come with a use case beyond this layer, there might be a chance that upstream would accept patches for that.

I will close this issue as there is not much I can do without upstream support

**Closed by priv-kweihmann** 2023-02-15 13:12 UTC
Labels: bug, Not our bug
